version: "3"
services:

  php8.2:
    tty: true
    build:
      context: .
      args:
        - PHP_VERSION=8.2
    volumes:
      - .:/var/www/html

  php8.3:
    tty: true
    build:
      context: .
      args:
        - PHP_VERSION=8.3
    volumes:
      - .:/var/www/html

  php8.4:
    tty: true
    build:
      context: .
      args:
        - PHP_VERSION=8.4
    volumes:
      - .:/var/www/html
