name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: PHP ${{ matrix.php }} / ${{ matrix.symfony }}
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.2"
          - "8.3"
          - "8.4"

        symfony:
          - symfony5

        include:
          - php: "8.2"
            symfony: symfony6
          - php: "8.3"
            symfony: symfony6
          - php: "8.2"
            symfony: symfony7
          - php: "8.3"
            symfony: symfony7
          - php: "8.4"
            symfony: symfony7

    env:
      MATRIX_PHP: ${{ matrix.php }}
      MATRIX_SYMFONY: ${{ matrix.symfony }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Install scenario
        run: |
          .scenarios.lock/install "${{ matrix.symfony }}" "${DEPENDENCIES}"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Show Chrome version
        run: chrome --version

      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Run unit tests
        run: vendor/bin/phpunit

      - name: Run Behat tests
        run: vendor/bin/behat --config=tests/Behat/behat.yml

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-php-${{ matrix.php }}-${{ matrix.symfony }}
          path: logs
